In [1]:
import numpy as np

In [4]:
x=np.arange(2,20)
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
sample_arrange=x

In [13]:
rand_array=np.random.randint(0,20,5)
rand_array

array([ 3,  6, 12, 11, 10])

In [9]:
sample_arrange.min()

2

In [15]:
rand_array.argmin()

0

In [14]:
rand_array.max()

12

In [16]:
sample_arrange.dtype

dtype('int64')

In [18]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
##T=transpose

In [22]:
import numpy as np

In [23]:
sample_array=np.arange(10,22)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [24]:
sample_array=sample_array.reshape(3,4)
sample_array

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [25]:
sample_array[2:]

array([[18, 19, 20, 21]])

In [27]:
sample_array[1]=100
sample_array

array([[ 10,  11,  12,  13],
       [100, 100, 100, 100],
       [ 18,  19,  20,  21]])

In [29]:
sample_array[:]=1001
sample_array

array([[1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001]])

In [30]:
##TWO DIMENSIONAL ARRAY

In [31]:
sample_matrix=np.array(([2,3,4],[4,5,6],[7,8,9]))
sample_matrix

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
sample_matrix[0][2]

4

In [34]:
## [0]= row
#[2]=column

In [36]:
sample_matrix[:0]

array([], shape=(0, 3), dtype=int64)

In [37]:
sample_matrix[1:,2:]

array([[6],
       [9]])

In [38]:
##sample techquines

In [39]:
import numpy as np

In [41]:
sample_array=np.arange(1,31)
sample_array
                       

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [43]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [44]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [45]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [46]:
np.max(sample_array)

30

In [47]:
np.min(sample_array)

1

In [48]:
np.argmin(sample_array)

0

In [49]:
np.argmax(sample_array)

29

In [50]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900])

In [51]:
np.std(sample_array)

8.65544144839919

In [52]:
np.var(sample_array)

74.91666666666667

In [53]:
#var= varaince
#std= standard deviation

In [54]:
np.mean(sample_array)

15.5

In [56]:
array=np.random.rand(3,4)
array

array([[0.54283737, 0.44843907, 0.09449987, 0.00991264],
       [0.21358188, 0.14297048, 0.34930097, 0.97417719],
       [0.17505164, 0.21607249, 0.71331358, 0.81602751]])

In [57]:
np.round(array,decimals=2)

array([[0.54, 0.45, 0.09, 0.01],
       [0.21, 0.14, 0.35, 0.97],
       [0.18, 0.22, 0.71, 0.82]])

In [58]:
sports=np.array(["golf","cricket","basketball","golf","kho-kho","football","basketball"])
np.unique(sports)

array(['basketball', 'cricket', 'football', 'golf', 'kho-kho'],
      dtype='<U10')